package com.litbo.hospitalzj.checklist.domain;

import lombok.Data;

import java.util.Date;

@Data
public class DcsjhyC {

  private Integer dcid;
  private Integer jcyqId;
  private Integer eqId;
  private String tester;
  private Date testTime;
  private String auditor;
  private String shrJcjl;
  private Date shsjTime;
  private String jcjl;
  private String jcsm;
  private Integer xlTest1;
  private Integer xlTest2;
  private Integer xlTest3;
  private Integer xlTest4;
  private Integer xlTest5;
  private Integer xlTest6;
  private Integer xlValue1;
  private Integer xlValue2;
  private Integer xlValue3;
  private Integer xlValue4;
  private Integer xlValue5;
  private Integer xlValue6;
  private String xlWc;
  private Integer xlResult;
  private Integer hxlTest1;
  private Integer hxlTest2;
  private Integer hxlTest3;
  private Integer hxlTest4;
  private Integer hxlTest5;
  private Integer hxlTest6;
  private Integer hxlValue1;
  private Integer hxlValue2;
  private Integer hxlValue3;
  private Integer hxlValue4;
  private Integer hxlValue5;
  private Integer hxlValue6;
  private String hxlWc;
  private Integer hxlResult;
  private Integer xybhdTest1;
  private Integer xybhdTest2;
  private Integer xybhdTest3;
  private Integer xybhdTest4;
  private Integer xybhdTest5;
  private Integer xybhdValue1;
  private Integer xybhdValue2;
  private Integer xybhdValue3;
  private Integer xybhdValue4;
  private Integer xybhdValue5;
  private String xybhdWc;
  private Integer xybhdResult;
  private Integer wcxyJtTest1;
  private Integer wcxyJtTest2;
  private Integer wcxyJtTest3;
  private Integer wcxyJtTest4;
  private Integer wcxyJtTest5;
  private Integer wcxyJtXsz1Value1;
  private Integer wcxyJtXsz1Value2;
  private Integer wcxyJtXsz1Value3;
  private Integer wcxyJtXsz1Value4;
  private Integer wcxyJtXsz1Value5;
  private Integer wcxyJtXsz2Value1;
  private Integer wcxyJtXsz2Value2;
  private Integer wcxyJtXsz2Value3;
  private Integer wcxyJtXsz2Value4;
  private Integer wcxyJtXsz2Value5;
  private Integer wcxyJtPjzValue1;
  private Integer wcxyJtPjzValue2;
  private Integer wcxyJtPjzValue3;
  private Integer wcxyJtPjzValue4;
  private Integer wcxyJtPjzValue5;
  private String wcxySyzWc;
  private String wcxyScWc;
  private Integer wcxyJtResult;
  private Integer wcdtxySdzTest1;
  private Integer wcdtxySdzTest2;
  private Integer wcdtxyXl;
  private Integer wcdtxyWc;
  private Integer wcdtxyValue1;
  private Integer wcdtxyValue2;
  private Integer wcdtxyValue3;
  private Integer wcdtxyValue4;
  private Integer wcdtxyValue5;
  private Integer wcdtxySsyValue;
  private Integer wcdtxySzyValue;
  private Integer wcdtxyResult;
  private Integer qmxjcYldTest1;
  private Integer qmxjcYldTest2;
  private String qmxjcWc;
  private Integer qmxjcYlszValue1;
  private Integer qmxjcYlszValue2;
  private Integer qmxjcYlszValue3;
  private Integer qmxjcYlszValue4;
  private Integer qmxjcQmxszValue1;
  private Integer qmxjcQmxszValue2;
  private Integer qmxjcResult;
  private Integer sgbjResult;
  private Integer bjxjcResult;
  private Integer jyjcResult;
  private String state;
  private String spare2;
  private String spare3;



}
